name: Build and Test

on:
  push:
    branches:
      - master
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [21] # Specify the Java versions to test with

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permissions for Gradle wrapper
        run: chmod +x gradlew 

      - name: Build the project
        run: ./gradlew clean build

      - name: Run unit tests
        run: ./gradlew test

      - name: Run Checkstyle for code style checks
        run: ./gradlew checkstyleMain checkstyleTest
